// @flow
export const SHOP_ACTION_TYPES = {
    GET_PRODUCTS_FAIL: "SHOP__GET_PRODUCTS_FAIL",
    GET_PRODUCTS_START: "SHOP__GET_PRODUCTS_START",
    GET_PRODUCTS_SUCCESS: "SHOP__GET_PRODUCTS_SUCCESS",
};
