// @flow

export const COMMON_ACTION_TYPES = {
    DECREMENT_CART_PRODUCTS_COUNT: 'COMMON__DECREMENT_CART_PRODUCTS_COUNT',
    INCREMENT_CART_PRODUCTS_COUNT: 'COMMON__INCREMENT_CART_PRODUCTS_COUNT',
    SHOW_MOBILE_MENU: 'COMMON__SHOW_MOBILE_MENU'
}
