// @flow

export const COMMON_ACTION_TYPES = {
    GET_USER_FAIL: "COMMON__GET_USER_FAIL",
    GET_USER_START: "COMMON__GET_USER_START",
    GET_USER_SUCCESS: "COMMON__GET_USER_SUCCESS",
    LOGIN_FAIL: "COMMON__LOGIN_FAIL",
    LOGIN_START: "COMMON__LOGIN_START",
    LOGIN_SUCCESS: "COMMON__LOGIN_SUCCESS",
    SELECT_LANG: "COMMON__SELECT_LANG",
    SHOW_MOBILE_MENU: "COMMON__SHOW_MOBILE_MENU",
    SIGNUP_FAIL: "COMMON__SIGNUP_FAIL",
    SIGNUP_START: "COMMON__SIGNUP_START",
    SIGNUP_SUCCESS: "COMMON__SIGNUP_SUCCESS",
};
