// @flow

export const COMMON_ACTION_TYPES = {
    SELECT_LANG: "COMMON__SELECT_LANG",
    SHOW_MOBILE_MENU: "COMMON__SHOW_MOBILE_MENU",
    SIGNUP_FAIL: "SIGNUP__SIGNUP_FAIL",
    SIGNUP_START: "SIGNUP__SIGNUP_START",
    SIGNUP_SUCCESS: "SIGNUP__SIGNUP_SUCCESS",
};
