// @flow
export const ADMIN_ACTION_TYPES = {
    CREATE_PRODUCT_FAIL: "ADMIN__CREATE_PRODUCT_FAIL",
    CREATE_PRODUCT_START: "ADMIN__CREATE_PRODUCT_START",
    CREATE_PRODUCT_SUCCESS: "ADMIN__CREATE_PRODUCT_SUCCESS",
};
